user_profile/accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.static import serve

from . import views

app_name = 'accounts'
urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),  # Used to upload image files, other files can also be uploaded word, ppt, etc.
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
    path('change-password/', views.change_password, name='change_password'),
    path('edit', views.edit_profile, name='edit'),
    path('login', views.sign_in, name='login'),
    path('logout', views.sign_out, name='logout'),
    path('profile', views.profile, name='profile'),
    path('register', views.register, name='register'),
    path('select-avatar', views.select_avatar, name='select_avatar'),
    path('crop-avatar', views.crop_avatar, name="crop_avatar"),
]
urlpatterns += staticfiles_urlpatterns()

user_profile/user_profile/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('summernote/', include('django_summernote.urls')),
    path('', views.index, name='index'),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/accounts/models.py
from django.contrib.auth.models import User
from django.db import models

from django_summernote.fields import SummernoteTextField


class UserProfile(models.Model):
    """A user profile model that extends the built-in user model"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='images/default.jpeg', upload_to='images')
    dob = models.DateField(null=True, blank=True)
    bio = SummernoteTextField(blank=True)
    location = models.CharField(max_length=255, blank=True)
    hobby = models.CharField(max_length=255, blank=True)

user_profile/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.files import File
from django.utils.translation import gettext, gettext_lazy as _

from bootstrap_datepicker_plus import DatePickerInput
from django_summernote.fields import SummernoteTextField
from django_summernote.widgets import SummernoteInplaceWidget

from . import models


def must_match_field(value):
    pass


class UserRegisterForm(UserCreationForm):
    """Form to allow users to register"""
    email = forms.EmailField()
    verify_email = forms.EmailField(label="Please verify your email address")
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput,
        help_text="""
        <ul>
            <li>Your password can't be too similar to your other personal information</li>
            <li>Your password can't be a commonly used password</li>
            <li>Your password can't be entirly numeric</li>
            <li>Your password must contain at least 14 characters</li>
            <li>Your password must contain uppercase and lowercase letters</li>
            <li>Your password must contain at least one numeric digit</li>
            <li>Your password must contain at least one special character</li>
        </ul>
        """
    )

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'verify_email',
            'password1',
            'password2',
        ]

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        verify = cleaned_data.get('verify_email')

        if email != verify:
            raise forms.ValidationError(
                "You need to enter the same email address in both fields"
            )

class UserUpdateForm(forms.ModelForm):
    """Form to allow users to update their user information"""
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
        )


class UserProfileUpdateForm(forms.ModelForm):
    """Form to allow users to update their profile information"""
    dob = forms.DateField(
        widget = DatePickerInput(format='%m/%d/%Y'),
        label = _("Date of Birth"),
        required = False,
    )

    class Meta:
        model = models.UserProfile
        fields = (
            'dob',
            'bio',
            'location',
            'hobby',
        )


class UserAvatarForm(forms.ModelForm):
    """Form to allow users to update their avatar"""
    avatar = forms.ImageField(widget=forms.FileInput)
    class Meta:
        model = models.UserProfile
        fields = ('avatar',)


class CropAvatarForm(forms.Form):
    """Form to allow users to crop their avatar"""
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())
    rotate = forms.IntegerField(widget=forms.HiddenInput())
    flip = forms.IntegerField(widget=forms.HiddenInput())

user_profile/accounts/views.py
from django.contrib import messages
from django.contrib.auth import (authenticate, login, logout,
                                 update_session_auth_hash)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from PIL import Image

from . import forms
from . import models


def sign_in(request):
    """Process the user login request"""
    form = AuthenticationForm
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    messages.success(
                        request,
                        f"You are now logged in as {user.username}"
                    )
                    return HttpResponseRedirect(reverse('index'))
                else:
                    messages.error(
                        request,
                        "That user account has been disabled"
                    )
            else:
                message.error(
                    request,
                    "The username or password is incorrect"
                )
    return render(
        request,
        'accounts/login.html',
        {'form': form, 'login_page': 'active'}
    )


def register(request):
    """Create new user account"""
    form = forms.UserRegisterForm()
    if request.method == 'POST':
        form = forms.UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username = form.cleaned_data['username'],
                email = form.cleaned_data['email'],
                password = form.cleaned_data['password1'],
            )
            login(request, user)
            messages.success(
                request,
                "You have successfully created a new acount and are " +
                f"now logged in as {user.username}"
            )
            return HttpResponseRedirect(reverse('index'))
    return render(
        request,
        'accounts/register.html',
        {'form': form, 'registration_page': 'active'}
    )


def sign_out(request):
    """Log the user out of the site"""
    logout(request)
    messages.success(request, "You've been logged out. Come back soon!")
    return HttpResponseRedirect(reverse('index'))


@login_required
def profile(request):
    """Display the details of the user's profile"""
    user = request.user
    user_profile = get_object_or_404(models.UserProfile, user_id=user.id)
    return render(
        request,
        'accounts/profile.html',
        {'user': user, 'user_profile': user_profile, 'profile_page': 'active'}
    )


@login_required
def edit_profile(request):
    """Edit the details of the user's profile"""
    if request.method == 'POST':
        user_update_form = forms.UserUpdateForm(
            request.POST,
            instance=request.user
        )
        user_profile_update_form = forms.UserProfileUpdateForm(
            request.POST,
            instance=request.user.userprofile
        )
        user_avatar_form = forms.UserAvatarForm(
            request.POST,
            request.FILES,
            instance=request.user.userprofile
        )
        if user_update_form.is_valid() and user_profile_update_form.is_valid():
            user_update_form.save()
            user_profile_update_form.save()
            user_avatar_form.save()
            messages.success(request, "Your profile has been updated!")
            return HttpResponseRedirect(reverse('accounts:profile'))
    else:
        user_update_form = forms.UserUpdateForm(
            instance=request.user
        )
        user_profile_update_form = forms.UserProfileUpdateForm(
            instance=request.user.userprofile
        )
        user_avatar_form = forms.UserAvatarForm(
            instance=request.user.userprofile
        )
    return render(request,
                  'accounts/edit_profile.html',
                  {
        'user_update_form': user_update_form,
        'user_profile_update_form': user_profile_update_form,
        'user_avatar_form': user_avatar_form,
        'edit_profile_page': 'active'
    })


@login_required
def change_password(request):
    """Allow the user to change their password"""
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(
                request,
                "Your password was successfully updated"
            )
            return HttpResponseRedirect(reverse('accounts:profile'))
        else:
            messages.error(request, "Please correct the error below")
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {'form': form})


@login_required
def select_avatar(request):
    """Allow user to select or change their avatar"""
    user = request.user
    user_profile = get_object_or_404(models.UserProfile, user_id=user.id)
    if request.method == 'POST':
        user_avatar_form = forms.UserAvatarForm(
            request.POST,
            request.FILES,
            instance=request.user.userprofile
        )
        if user_avatar_form.is_valid():
            user_avatar_form.save()
            return HttpResponseRedirect(reverse('accounts:crop_avatar'))
    else:
        user_avatar_form = forms.UserAvatarForm(
            instance=request.user.userprofile
        )
    return render(
        request,
        'accounts/select_avatar.html',
        {
        'user': user,
        'user_profile': user_profile,
        'user_avatar_form': user_avatar_form
        }
    )


@login_required
def crop_avatar(request):
    """Allow user to crop their avatar"""
    user = request.user
    user_profile = get_object_or_404(models.UserProfile, user_id=user.id)
    if request.method == 'POST':
        crop_avatar_form = forms.CropAvatarForm(
        request.POST,
        request.FILES
        )
        if crop_avatar_form.is_valid():
            x = crop_avatar_form.cleaned_data['x']
            y = crop_avatar_form.cleaned_data['y']
            w = crop_avatar_form.cleaned_data['width']
            h = crop_avatar_form.cleaned_data['height']
            rotate = crop_avatar_form.cleaned_data['rotate']
            flip = crop_avatar_form.cleaned_data['flip']

            image = Image.open(user_profile.avatar)
            if flip == -1:
                image = image.transpose(method=Image.FLIP_LEFT_RIGHT)
            rotated_image = image.rotate(-rotate, expand=True)
            cropped_image = rotated_image.crop((x, y, w+x, y+h))
            cropped_image.save(user_profile.avatar.path)
            return HttpResponseRedirect(reverse('accounts:edit'))
    else:
        crop_avatar_form = forms.CropAvatarForm()
    return render(
        request,
        'accounts/crop_avatar.html',
        {
        'user': user,
        'user_profile': user_profile,
        'crop_avatar_form': crop_avatar_form
        }
    )

user_profile/accounts/templates/accounts/change_password.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %}Change Password{% endblock %}

{% block content %}
  <div class="container my-4">
    <form method="POST">
      {% csrf_token %}
      {{ form|crispy }}
      <button id="saveBtn" class="btn btn-dark" type="submit">Save New Password</button>
    </form>
  </div>
{% endblock %}

{% block js %}
  <script src="{% static "js/accounts.js" %}" type="text/javascript" charset="utf-8"></script>
{% endblock %}

user_profile/accounts/templates/accounts/crop_avatar.html
{% extends 'layout.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Edit Profile{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static "css/cropper.min.css" %}">
  <link rel="stylesheet" href="{% static "css/cropper-style.css" %}">
{% endblock %}

{% block content %}
  <h1>Crop Your Avatar</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ crop_avatar_form }}


    <div class="crop-box-square my-3">
      <img id="image" src="{{ user.userprofile.avatar.url }}">
    </div>
    <button class="btn btn-dark" type="button" onclick="cropper.rotate(-90);"><i data-feather="corner-left-down"></i></button>
    <button class="btn btn-dark" type="button" onclick="cropper.rotate(90);"><i data-feather="corner-right-down"></i></button>
    <button class="btn btn-secondary" type="button" aria-pressed="false" id="flipToggle"><i data-feather="arrow-left"></i><i data-feather="arrow-right"></i></button>
    <button class="btn btn-dark" type="submit">Create New Avatar</button>

  </form>

{% endblock %}

{% block js %}
  <script src="{% static "js/cropper.js" %}" type="text/javascript" charset="utf-8"></script>
  <script src="{% static "js/crop_avatar.js" %}" type="text/javascript" charset="utf-8"></script>
{% endblock %}

user_profile/accounts/templates/accounts/edit_avatar.html
{% extends 'layout.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Edit Profile{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static "css/cropper.min.css" %}">
  <link rel="stylesheet" href="{% static "css/cropper-style.css" %}">
{% endblock %}

{% block content %}
  <div class="container my-4">
    <h1>Edit Profile</h1>
    <img class="pl-0 my-3" src="{{ user.userprofile.avatar.url }}" id="image">
  </div>
{% endblock %}

{% block js %}
  <script src="{% static "js/cropper.js" %}" type="text/javascript" charset="utf-8"></script>
  <script src="{% static "js/crop_avatar.js" %}" type="text/javascript" charset="utf-8"></script>
{% endblock %}

user_profile/accounts/templates/accounts/edit_profile.html
{% extends 'layout.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Edit Profile{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static "css/cropper.min.css" %}">
  <link rel="stylesheet" href="{% static "css/cropper-style.css" %}">
{% endblock %}

{% block content %}
  <div class="container my-4">
    <h1>Edit Profile</h1>
    <img class="col-5 pl-0 my-3" src="{{ user.userprofile.avatar.url }}">
    <a href="{% url 'accounts:select_avatar' %}"><p class="btn btn-dark">Change Avatar</p></a>
    <form method="POST" enctype="multipart/form-data" id="formUpload">
      {% csrf_token %}
      {{ user_update_form|crispy }}
      {{ user_profile_update_form|crispy }}
      {{ user_profile_update_form.media }}
      <button class="btn btn-dark" type="submit">Save Changes</button>
    </form>
  </div>
{% endblock %}

user_profile/accounts/templates/accounts/login.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}

{% block content %}
  <div class="container my-4">
    <form method="POST" action="{% url 'accounts:login' %}">
      <div class="form-group">
        {% csrf_token %}
        {{ form|crispy }}
      </div>
      <button class="btn btn-dark" type="submit">Login</button>
    </form>
  </div>
{% endblock %}

user_profile/accounts/templates/accounts/profile.html
{% extends 'layout.html' %}

{% block title %}
  {% if user.first_name %}
    {{ user.first_name }}'s Profile
    {% else %}
    {{ user.username }} | Profile
  {% endif %}
{% endblock %}

{% block content %}
  <div class="jumbotron">

    <img class="col-3" src="{{ user.userprofile.avatar.url }}">
    {% if user.first_name or user.last_name %}
      <h1 class="display-4 ml-2 list-inline-item align-bottom">{{ user.first_name }} {{ user.last_name }}</h1>
    {% else %}
      <h1 class="display-4 ml-2 list-inline-item align-bottom">{{ user.username }}</h1>
    {% endif %}
  </div>
  <div class="container mt-2">
    {% if user.email %}
    <h3>Email</h3>
    <p>{{ user.email }}</p>
    {% endif %}
    {% if user_profile.bio %}
    <h3>Bio</h3>
    <p>{{ user_profile.bio|safe }}</p>
    {% endif %}
    {% if user_profile.dob %}
    <h3>DOB</h3>
    <p>{{ user_profile.dob }}</p>
    {% endif %}
    {% if user_profile.location %}
    <h3>Location</h3>
    <p>{{ user_profile.location }}</p>
    {% endif %}
    {% if user_profile.hobby %}
    <h3>Favorite Hobby</h3>
    <p>{{ user_profile.hobby }}</p>
    {% endif %}
  </div>
    <hr>
  <div class="container">
    <p><a href="{% url 'accounts:edit' %}" class="text-dark text-decoration-none"><i data-feather="edit" class="align-top"></i> Edit your profile</a> | <a href="{% url 'accounts:change_password' %}" class="text-dark text-decoration-none"><i data-feather="unlock" class="align-top"></i> Change your password</a></p>
  </div>
{% endblock %}

user_profile/accounts/templates/accounts/register.html
{% extends 'layout.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="container my-4">
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button id="saveBtn" class="btn btn-dark" type="submit">Register</button>
  </form>
</div>
{% endblock %}

{% block js %}
  <script src="{% static "js/accounts.js" %}" type="text/javascript" charset="utf-8"></script>
{% endblock %}

user_profile/accounts/templates/accounts/select_avatar.html
{% extends 'layout.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
  <h1>Choose a Photo to Crop</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_avatar_form|crispy }}
    <a href="{% url 'accounts:edit' %}"><button type="button" class="btn btn-secondary" name="cancel">Cancel</button></a>
    <button class="btn btn-dark" type="submit">Continue to Crop<i data-feather="arrow-right"></i></button>
    <p>* If you continue to crop you will not be able to revert to your previous avatar.</p>
  </form>

{% endblock %}

user_profile/accounts/templates/accounts/test_form.html
{% extends 'layout.html' %}

{% block title %}Test{% endblock %}

{% block content %}
  <form method="POST" action="{% url 'accounts:test_form' %}">
    {% csrf_token %}
    First name:<br>
    <input type="text" name="firstname"><br>
    Last name:<br>
    <input type="text" name="lastname">
    <input type="submit" value="Submit">
  </form>
{% endblock %}