user_profile/accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views.static import serve

from . import views

app_name = 'accounts'
urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),  # Used to upload image files, other files can also be uploaded word, ppt, etc.
    path('static/<path:path>', serve, {'document_root': settings.STATIC_ROOT}),
    path('change-password/', views.change_password, name='change_password'),
    path('edit', views.edit_profile, name='edit'),
    path('login', views.sign_in, name='login'),
    path('logout', views.sign_out, name='logout'),
    path('profile', views.profile, name='profile'),
    path('register', views.register, name='register'),
    path('select-avatar', views.select_avatar, name='select_avatar'),
    path('crop-avatar', views.crop_avatar, name="crop_avatar"),
]
urlpatterns += staticfiles_urlpatterns()

user_profile/user_profile/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('summernote/', include('django_summernote.urls')),
    path('', views.index, name='index'),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/templates/index.html
{% extends 'layout.html' %}

{% block title %}Home{% endblock %}


{% block content %}
  <div class="jumbotron jumbotron-fluid" style="margin-bottom: 0px">
    {% if user.is_authenticated %}
      {% if user.first_name %}
        <h1 class="display-4 mb-4 text-center">Hello, {{ user.first_name }}!</h1>
      {% else %}
        <h1 class="display-4 mb-4 text-center">Hello, {{ user.username }}!</h1>
      {% endif %}
      {% if not user.first_name %}
        <p class="lead text-center"><a class="text-black-50 text-decoration-none" href="{% url 'accounts:edit' %}">Add some information</a> to your <a class="text-black-50 text-decoration-none" href="{% url 'accounts:profile' %}">profile</p>
      {% else %}
        <img class="col-3 mx-auto d-block" src="{{ user.userprofile.avatar.url }}">
        <p class="lead mt-2 text-center">Check out your <a class="text-black-50 text-decoration-none" href="{% url 'accounts:profile' %}">profile<i data-feather="arrow-right"></i></a></p>
      {% endif %}
    {% else %}
      <h1 class="display-4 text-center">Sign up and create a profile!</h1>
      <p class="lead mt-2 text-center"><a class="text-black-50 text-decoration-none" href="{% url 'accounts:register' %}">Register</a> a new account, or <a class="text-black-50 text-decoration-none" href="{% url 'accounts:login' %}">login</a> if you already have one</p>
    {% endif %}
  </div>
{% endblock %}

user_profile/templates/layout.html
{% load static %}

<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" type="image/jpg" href="{% static "images/favicon.ico" %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
    <!-- Bootstrap CSS, Popper, and Javascript -->
    <script src="{% static "js/jquery-3.4.1.min.js" %}" type="text/javascript" charset="utf-8"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!-- Feather for Bootstrap icons -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>

    <link rel="stylesheet" href="{% static "css/global.css" %}">
    {% block head %}{% endblock %}
  </head>
  <header>
    <!-- Navbar -->
    <nav class="navbar navbar-dark bg-dark navbar-default px-5">
      <ul class="navbar-nav mx-5 px-5 flex-row">
        <li class="nav-item {{ index_page }} "><a class="nav-link" href="{% url 'index' %}"><i data-feather="home" class="align-top"></i> Home</a></li>
        {% if user.is_authenticated %}
          <li class="nav-item {{ profile_page }} "><a class="nav-link ml-3" href="{% url 'accounts:profile' %}"><i data-feather="user" class="align-top"></i> Profile</a></li>
        {% endif %}
      </ul>
      <ul class="navbar-nav mx-5 px-5 flex-row">
        {% if not user.is_authenticated %}
          <li class="nav-item mr-4 {{ registration_page }}"><a class="nav-link" href="{% url 'accounts:register' %}">Register <i data-feather="user-plus"></i></a></li>
          <li class="nav-item {{ login_page }}"><a class="nav-link" href="{% url 'accounts:login' %}">Login<i data-feather="log-in"></i></a></li>
        {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}"><i data-feather="log-out"></i>Logout</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <body>

    <!-- Messages -->
    <div class="container-fluid position-fixed" id="flash_messages">
      {% if messages %}
          <div class="">
              <div class="">
                  {% for message in messages %}
                      <div class="alert alert-{{ message.tags }}">
                          {{ message }}
                      </div>
                  {% endfor %}
              </div>
          </div>
      {% endif %}
    </div>

    <!-- Page Content -->
    <div class="container">{% block content %}{% endblock %}</div>

    <!-- Feather script -->
    <script>feather.replace({ 'height': 20, 'stroke-width': 2 })</script>

    <!-- Custom jQuery for Bootstrap -->
    <script src="{% static "js/user_profile.js" %}" type="text/javascript" charset="utf-8"></script>
    {% block js %}{% endblock %}
  </body>
</html>